---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
overrides:
#! featuregates
- image: featuregates-controller-manager:latest
  newImage: projects-stg.registry.vmware.com/tkg/calico-all/pod2daemon:v3.11.3_vmware.1