#@ load("@ytt:data", "data")
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tanzu-auth-controller-manager
subjects:
  - kind: ServiceAccount
    name: tanzu-auth-controller-manager-sa
    namespace: #@ data.values.namespace
roleRef:
  kind: ClusterRole
  name: tanzu-auth-controller-manager
  apiGroup: rbac.authorization.k8s.io
