#@data/values
#@overlay/match-child-defaults missing_ok=True
---
namespace: tkg-system
deployment:
  hostNetwork: false
  nodeSelector: null
  tolerations: []
  #! If hostNetwork is set to true the below two ports should be different
  tkrConversionWebhookServerPort: 9443
  tkrResolverWebhookServerPort: 9443
