#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tanzu-framework
  namespace: #@ data.values.frameworkPackage.namespaceForPackageInstallation
  annotations:
    kapp.k14s.io/change-group: "framework-packageinstall/tanzu-framework"
    kapp.k14s.io/change-rule.0: "upsert after upserting framework-packageinstall/serviceaccount"
    kapp.k14s.io/change-rule.1: "delete before deleting framework-packageinstall/serviceaccount"
  labels:
    tkg.tanzu.vmware.com/package-type: "management"
spec:
  serviceAccountName: tanzu-framework-package-sa
  packageRef:
    refName: framework.tanzu.vmware.com
    versionSelection:
      prereleases: {}
      #@ if data.values.frameworkPackage.versionConstraints:
      constraints: #@ data.values.frameworkPackage.versionConstraints
      #@ end
  values:
    - secretRef:
        name: tanzu-framework-values
---
apiVersion: v1
kind: Secret
metadata:
  name: tanzu-framework-values
  namespace: #@ data.values.frameworkPackage.namespaceForPackageInstallation
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting framework-packageinstall/serviceaccount"
    kapp.k14s.io/change-rule.1: "delete before deleting framework-packageinstall/serviceaccount"
type: Opaque
stringData:
  values.yaml: #@ yaml.encode(data.values.frameworkPackage)
