#@ load("@ytt:data", "data")
#@ load("package-helpers.lib.yaml", "get_package_repository")

#@ package_repository = get_package_repository(data.values.packageRepository)

---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
#@ for package in package_repository.packages:
#@ imagePackageVersion = "v" + package.version + "_" + package.packageSubVersion
- annotations:
    kbld.carvel.dev/id: #@ "{}/{}:{}".format(package_repository.registry, package.name, imagePackageVersion)
  image: #@ "{}/{}@sha256:{}".format(package_repository.registry, package.name, package.sha256)
#@ end
kind: ImagesLock
